[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "euterpe"
description = "lib for music theory"
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3.12",
]
requires-python = "==3.12.*"
dependencies = [
    "dacite==1.8.1"
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "mypy"
]

[tool.setuptools]
package-dir = { "" = "src" }