name: 🌱 Create Branch from Issue
on:
  issues:
    types: [assigned]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, closed]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        id: Create_Issue_Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
